### ISSUE TITLE
Feature Request: Include URL encoder/decoder

### ISSUE THREAD

**Issue by msarkrish** [PolyglotNetwork/devtoolbox#12]
Example Site: https://www.urldecoder.org/

**Comment by msarkrish** [comment]
This feature is already implemented, need new release with URL encoder/deocder

**Comment by nileshtrivedi** [comment]
@msarkrish : I uploaded mac os build with latest changes: https://github.com/PolyglotNetwork/devtoolbox/releases/tag/v0.3.0

**Comment by msarkrish** [comment]
@nileshtrivedi I have attached the windows build:
[Windows Release.zip](https://github.com/PolyglotNetwork/devtoolbox/files/8597613/Windows.Release.zip)

**Comment by msarkrish** [comment]
@nileshtrivedi I have attached the windows build
