### ISSUE TITLE
Test on Linux

### ISSUE THREAD

**Issue by nileshtrivedi** [PolyglotNetwork/devtoolbox#3]

**Comment by soham1sawant** [comment]
I want to test the app on Linux. I'm using Fedora Linux 35. How should I go forward ? I have the latest version of flutter stable installed.

**Comment by nileshtrivedi** [comment]
@soham1sawant Have you tried `flutter run -d linux` ? [Refer to Flutter Desktop docs](https://docs.flutter.dev/desktop)

**Comment by soham1sawant** [comment]
The app works perfectly fine on Linux.
